### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by jaytimbadia** [pranavpsv/Genre-Based-Story-Generator#2]
Hi,

Great work!!

Will it be possible to provide a pre-trained model if possible for different genres?
I do not have the resources to train the model.

Thanks in Advance!!

**Comment by pranavpsv** [comment]
Hey,

Thank you, this model is using a pre-trained GPT2 checkpoint that is fine-tuned on the data in this repository. 

The fine-tuned model checkpoint is stored in the Huggingface model hub under the model name "pranavpsv/gpt2-genre-story-generator".

If you want to load the fine-tuned model checkpoint to generate stories by downloading and using the checkpoint directly instead of training the pre-trained GPT-2 model, here's the way:

```python
from transformers import pipeline
# downloads and stores the checkpoint in a cache directory
story_gen = pipeline("text-generation", "pranavpsv/gpt2-genre-story-generator")

# If you want to use the pipeline for generation directly
print(story_gen("<BOS> <scifi> In an effort to discover other habitable exoplanets,", max_length=100))
```
